// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

// ReleaseTrack represents a gcloud release track.
type ReleaseTrack string

const (
	// Alpha release track.
	Alpha ReleaseTrack = "ALPHA"
	// Beta release track.
	Beta ReleaseTrack = "BETA"
	// GA release track.
	GA ReleaseTrack = "GA"
)

// Surface represents the top-level collection of command trees.
type Surface struct {
	Root   *CommandGroup
	Tracks []ReleaseTrack
}

// CommandGroup defines the metadata for a structural grouping of gcloud commands
// (typically mapping to an API service or an AIP-122 Resource collection).
// It is used to generate the Python `__init__.py` registration files.
type CommandGroup struct {
	ClassName string
	FileName  string
	HelpText  string
	Commands  map[string]*Command
	Groups    map[string]*CommandGroup
}

// Command represents the top-level structure for a gcloud command definition.
// This struct is pure domain logic and separates CLI intent from the YAML output schema.
type Command struct {
	// Name specifies the name of the command.
	Name string

	// Hidden specifies whether this command should be hidden from the user in
	// help text and command listings.
	// Origin: Hardcoded to `true` by this generator.
	Hidden bool

	// HelpText contains the brief and detailed help text for the command.
	// Origin: Populated from `method_rules` in the `gcloud.yaml` config file.
	HelpText HelpText

	// Arguments defines the set of flags and positional arguments for the command.
	// Origin: Generated by parsing the fields of the method's request message from the proto.
	Arguments []Argument

	// APIVersion is the version of the API to call (e.g., "v1").
	// Origin: Derived from the `api_version` field in the `gcloud.yaml` config file.
	APIVersion string

	// Collection is the list of API collections that this command operates on.
	// Origin: Constructed from the API service name and the resource's collection path.
	Collection []string

	// Method is the name of the API method to call.
	Method string

	// Async specifies the configuration for handling long-running operations.
	// Origin: Generated by `newAsync` if the proto method is annotated as a long-running operation.
	Async *Async

	// ResponseIDField is the name of the field in the response that contains the resource ID.
	// Origin: Derived from `ResourceMethodParams`.
	ResponseIDField string

	// ReadModifyUpdate indicates whether to use a read-modify-update cycle for Update commands.
	ReadModifyUpdate bool

	// DisableAutoFieldMask disables the field mask auto generation.
	DisableAutoFieldMask bool

	// StarUpdateMask indicates whether to add updateMask="*" to static_fields in request.
	StarUpdateMask bool

	// OutputFormat is the output format for the command (e.g., "table(name, ...)").
	OutputFormat string
}

// HelpText holds the brief and detailed help text for the command.
type HelpText struct {
	// Brief is a short, one-line summary of what the command does.
	// Origin: From the `brief` field in a `method_rule` in `gcloud.yaml`.
	Brief string
	// Description is a more detailed explanation of the command's functionality.
	// Origin: From the `description` field in a `method_rule` in `gcloud.yaml`.
	Description string
	// Examples provides one or more examples of how to use the command.
	// Origin: From the `examples` field in a `method_rule` in `gcloud.yaml`.
	Examples string
}

// Async defines the details for handling long-running operations.
type Async struct {
	// Collection is the API collection for the long-running operation resource.
	// Origin: Hardcoded to the standard operations collection for the service.
	Collection []string

	// ExtractResourceResult indicates whether to extract the resource result from the LRO.
	ExtractResourceResult bool
}
