// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/iancoleman/strcase"
)

type surfaceWriter struct {
	outputDir  string
	baseModule string
	tracks     []string
}

func writeSurface(outputDir string, baseModule string, surface *Surface) error {
	w := &surfaceWriter{
		outputDir:  outputDir,
		baseModule: baseModule,
		tracks:     surface.Tracks,
	}
	return w.writeGroup(surface.Root, nil)
}

func (w *surfaceWriter) writeGroup(g *CommandGroup, parentPath []string) error {
	if g == nil {
		return nil
	}

	path := append(parentPath, strcase.ToSnake(g.FileName))
	groupDir := filepath.Join(w.outputDir, filepath.Join(path...))
	if err := os.MkdirAll(groupDir, 0755); err != nil {
		return err
	}

	if err := w.writeCommandGroupFile(g, path); err != nil {
		return err
	}

	if err := w.writeGroupCommands(g, path); err != nil {
		return err
	}

	return w.writeGroupSubgroups(g, path)
}

func (w *surfaceWriter) writeGroupCommands(g *CommandGroup, path []string) error {
	groupDir := filepath.Join(w.outputDir, filepath.Join(path...))

	for verb, cmd := range g.Commands {
		if err := writeCommandFiles(groupDir, verb, cmd, w.tracks); err != nil {
			return err
		}
	}
	return nil
}

func (w *surfaceWriter) writeGroupSubgroups(g *CommandGroup, path []string) error {
	for _, subGroup := range g.Groups {
		if err := w.writeGroup(subGroup, path); err != nil {
			return err
		}
	}
	return nil
}

func (w *surfaceWriter) writeCommandGroupFile(g *CommandGroup, path []string) error {
	groupDir := filepath.Join(w.outputDir, filepath.Join(path...))
	if err := os.MkdirAll(groupDir, 0755); err != nil {
		return err
	}
	initPath := filepath.Join(groupDir, "__init__.py")
	extPath := filepath.Join(groupDir, "_init_extensions.py")

	primaryHelpText := g.HelpText
	var trackViews []trackView
	for _, t := range w.tracks {
		var suffix string
		switch t {
		case "GA":
			suffix = "Ga"
		case "BETA":
			suffix = "Beta"
		case "ALPHA":
			suffix = "Alpha"
		}
		trackViews = append(trackViews, trackView{Name: t, Suffix: suffix})
	}

	modulePathParts := make([]string, 0, 2+len(path))
	if w.baseModule != "" {
		modulePathParts = append(modulePathParts, w.baseModule)
		modulePathParts = append(modulePathParts, "surface")
	}
	modulePathParts = append(modulePathParts, path...)
	fullModulePath := strings.Join(modulePathParts, ".")

	isRoot := len(path) <= 1

	view := commandGroupView{
		ClassName:  g.ClassName,
		ModulePath: fullModulePath,
		HelpText:   primaryHelpText,
		Year:       time.Now().Year(),
		IsRoot:     isRoot,
		Tracks:     trackViews,
	}

	var buf bytes.Buffer
	if err := commandGroupTemplate.Execute(&buf, view); err != nil {
		return err
	}

	if err := os.WriteFile(initPath, []byte(strings.TrimSpace(buf.String())+"\n"), 0644); err != nil {
		return err
	}

	buf.Reset()
	if err := initExtensionsTemplate.Execute(&buf, view); err != nil {
		return err
	}

	return os.WriteFile(extPath, []byte(strings.TrimSpace(buf.String())+"\n"), 0644)
}

type trackView struct {
	Name   string
	Suffix string
}

type commandGroupView struct {
	ClassName  string
	ModulePath string
	HelpText   string
	Year       int
	IsRoot     bool
	Tracks     []trackView
}

var commandGroupTemplate = template.Must(template.New("__init__.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(autogenTemplate + `"""{{.HelpText}}"""

from googlecloudsdk.calliope import base
from {{.ModulePath}} import _init_extensions as extensions


{{range .Tracks}}@base.ReleaseTracks(base.ReleaseTrack.{{.Name}})
@base.Autogenerated
class {{$.ClassName | toCamel}}{{.Suffix}}(extensions.{{$.ClassName | toCamel}}{{.Suffix}}):
  """{{$.HelpText}}"""


{{end}}
`))

var initExtensionsTemplate = template.Must(template.New("_init_extensions.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(licenseTemplate + `"""File to add optional custom code to extend __init__.py."""` + "\n" + `from googlecloudsdk.calliope import base


class {{$.ClassName | toCamel}}Alpha(base.Group):
  """Optional no-auto-generated code for ALPHA."""
{{if .IsRoot}}  category = base.UNCATEGORIZED_CATEGORY
{{end}}

class {{$.ClassName | toCamel}}Beta(base.Group):
  """Optional no-auto-generated code for BETA."""
{{if .IsRoot}}  category = base.UNCATEGORIZED_CATEGORY
{{end}}

class {{$.ClassName | toCamel}}Ga(base.Group):
  """Optional no-auto-generated code for GA."""
{{if .IsRoot}}  category = base.UNCATEGORIZED_CATEGORY
{{end}}`))
