// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/librarian"
	"github.com/googleapis/librarian/internal/yaml"
)

// nodejsConfigFiles lists per-library config files generated by
// gapic-generator-typescript that are redundant in the monorepo. They are
// preserved during migration to avoid noisy diffs.
var nodejsConfigFiles = []string{
	".eslintignore",
	".eslintrc.json",
	".eslintrc.yml",
	".gitattributes",
	".gitignore",
	".jsdoc.js",
	".mocharc.js",
	".mocharc.json",
	".nycrc",
	".prettierignore",
	".prettierrc.cjs",
	".prettierrc.js",
	".readme-partials.yaml",
	".readme-partials.yml",
	".repo-metadata.json",
	"CHANGELOG.md",
	"CODE_OF_CONDUCT.md",
	"CONTRIBUTING.md",
	"LICENSE",
	"README.md",
	"librarian.js",
	"linkinator.config.json",
	"package.json",
	"tsconfig.json",
	"tslint.json",
	"webpack.config.js",
}

// nodejsPackageJSON represents the fields we need from a Node.js package.json.
type nodejsPackageJSON struct {
	Name         string            `json:"name"`
	Version      string            `json:"version"`
	Dependencies map[string]string `json:"dependencies"`
}

// owlBotYAML represents the fields we need from an .OwlBot.yaml.
type owlBotYAML struct {
	DeepCopyRegex []owlBotCopyRule `yaml:"deep-copy-regex"`
}

// owlBotCopyRule represents a copy rule in .OwlBot.yaml.
type owlBotCopyRule struct {
	Source string `yaml:"source"`
	Dest   string `yaml:"dest"`
}

// nodejsGapicInfo contains information from the nodejs_gapic_library rule.
type nodejsGapicInfo struct {
	packageName           string
	bundleConfig          string
	diregapic             bool
	extraProtocParameters []string
	handwrittenLayer      bool
	mainService           string
	mixins                string
}

// owlBotSourceRegex extracts the base API path from an .OwlBot.yaml
// deep-copy-regex source pattern. The pattern is usually of the form:
// /some/path/(version-regex)/.*-nodejs, or /some/path/[^/]+-nodejs,
// or /some_path-nodejs.
var owlBotSourceRegex = regexp.MustCompile(`^/(?:(.+?)/(?:\(|v\d|[^/]+-nodejs)|([^/]+)-nodejs)`)

func runNodejsMigration(ctx context.Context, repoPath string) error {
	src, err := fetchSource(ctx)
	if err != nil {
		return errFetchSource
	}

	libraries, err := buildNodejsLibraries(repoPath, src.Dir)
	if err != nil {
		return err
	}

	sort.Slice(libraries, func(i, j int) bool {
		return libraries[i].Name < libraries[j].Name
	})

	cfg := &config.Config{
		Language: config.LanguageNodejs,
		Repo:     "googleapis/google-cloud-node",
		Sources: &config.Sources{
			Googleapis: src,
		},
		Default: &config.Default{
			Output: "packages",
		},
		Libraries: libraries,
	}
	cfg.Sources.Googleapis.Dir = ""

	if err := librarian.RunTidyOnConfig(ctx, repoPath, cfg); err != nil {
		return fmt.Errorf("librarian tidy failed: %w", err)
	}
	return nil
}

func buildNodejsLibraries(repoPath, googleapisDir string) ([]*config.Library, error) {
	packagesDir := filepath.Join(repoPath, "packages")
	entries, err := os.ReadDir(packagesDir)
	if err != nil {
		return nil, err
	}

	var libraries []*config.Library
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		library, err := buildNodejsLibrary(googleapisDir, packagesDir, entry.Name())
		if err != nil {
			return nil, err
		}

		libraries = append(libraries, library)
	}
	return libraries, nil
}

func buildNodejsLibrary(googleapisDir, packagesDir, libraryName string) (*config.Library, error) {
	pkgDir := filepath.Join(packagesDir, libraryName)

	// Read package.json.
	pkgJSON, err := readNodejsPackageJSON(filepath.Join(pkgDir, "package.json"))
	if err != nil {
		return nil, fmt.Errorf("reading package.json for %s: %w", libraryName, err)
	}

	library := &config.Library{
		Name:    libraryName,
		Version: pkgJSON.Version,
		Nodejs:  &config.NodejsPackage{},
	}

	// Read .OwlBot.yaml to get API paths.
	owlBotPath := filepath.Join(pkgDir, ".OwlBot.yaml")
	if _, statErr := os.Stat(owlBotPath); statErr == nil {
		owlBot, err := yaml.Read[owlBotYAML](owlBotPath)
		if err != nil {
			return nil, fmt.Errorf("reading .OwlBot.yaml for %s: %w", libraryName, err)
		}
		apis, err := parseOwlBotAPIPaths(owlBot, googleapisDir, pkgJSON.Name)
		if err != nil {
			return nil, fmt.Errorf("parsing API paths for %s: %w", libraryName, err)
		}

		var filteredAPIs []*config.API
		for _, api := range apis {
			if libraryName == "google-cloud-compute" && api.Path == "google/cloud/compute/v1small" {
				continue
			}
			filteredAPIs = append(filteredAPIs, api)
		}
		library.APIs = filteredAPIs
		library.Nodejs.NodejsAPIs = buildNodejsLibraryAPIs(googleapisDir, filteredAPIs)
	}

	// Extract copyright year from existing generated source files.
	if year := extractCopyrightYear(pkgDir); year != "" {
		library.CopyrightYear = year
	}

	// Check if the npm package name needs to be set explicitly.
	if derivedName := deriveNpmPackageName(libraryName); pkgJSON.Name != derivedName {
		library.Nodejs.PackageName = pkgJSON.Name
	}

	// Extract extra dependencies (beyond google-gax).
	extraDeps := make(map[string]string)
	for dep, version := range pkgJSON.Dependencies {
		if dep != "google-gax" {
			extraDeps[dep] = version
		}
	}
	if len(extraDeps) > 0 {
		library.Nodejs.Dependencies = extraDeps
	}

	// Apply BUILD.bazel fields to the library config.
	if len(library.APIs) > 0 {
		info, err := parseBazelNodejsInfo(googleapisDir, library.APIs[0].Path)
		if err == nil && info != nil {
			if info.bundleConfig != "" {
				library.Nodejs.BundleConfig = info.bundleConfig
			}
			if len(info.extraProtocParameters) > 0 {
				library.Nodejs.ExtraProtocParameters = info.extraProtocParameters
			}
			if info.handwrittenLayer {
				library.Nodejs.HandwrittenLayer = true
			}
			if info.mainService != "" {
				library.Nodejs.MainService = info.mainService
			}
			if info.mixins != "" {
				library.Nodejs.Mixins = info.mixins
			}
		}
	}

	for _, name := range nodejsConfigFiles {
		if _, err := os.Stat(filepath.Join(pkgDir, name)); err == nil {
			library.Keep = append(library.Keep, name)
		}
	}
	for _, dir := range []string{"samples", "system-test"} {
		dirKeep, err := nodejsSubdirKeep(pkgDir, dir)
		if err != nil {
			return nil, fmt.Errorf("collecting %s for %s: %w", dir, libraryName, err)
		}
		library.Keep = append(library.Keep, dirKeep...)
	}

	if libraryName == "google-cloud-compute" {
		v1smallKeep, err := nodejsV1SmallKeep(pkgDir)
		if err != nil {
			return nil, fmt.Errorf("collecting keep files for v1small: %w", err)
		}
		library.Keep = append(library.Keep, v1smallKeep...)
	}

	return library, nil
}

// TODO(https://github.com/googleapis/google-cloud-node/issues/8149): Do not
// generate or delete v1small. This package is not meant to be used and
// will be deprecated and removed in a future major release. Remove this workaround once resolved.
//
// We explicitly add these files to the keep list to prevent the clean
// phase from deleting them, as the generation phase skips v1small.
func nodejsV1SmallKeep(pkgDir string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(pkgDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "node_modules" || d.Name() == "owl-bot-staging" {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(pkgDir, path)
		if err != nil {
			return err
		}
		if strings.Contains(rel, "v1small") {
			paths = append(paths, rel)
		}
		return nil
	})
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	return paths, nil
}

func buildNodejsLibraryAPIs(googleapisDir string, apis []*config.API) []*config.NodejsAPI {
	var nodejsAPIs []*config.NodejsAPI
	for _, api := range apis {
		info, err := parseBazelNodejsInfo(googleapisDir, api.Path)
		if err == nil && info != nil && info.diregapic {
			nodejsAPIs = append(nodejsAPIs, &config.NodejsAPI{
				Path:      api.Path,
				DIREGAPIC: true,
			})
		}
	}
	return nodejsAPIs
}

func readNodejsPackageJSON(path string) (*nodejsPackageJSON, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	pkg := &nodejsPackageJSON{}
	if err := json.Unmarshal(data, pkg); err != nil {
		return nil, err
	}
	return pkg, nil
}

// parseOwlBotAPIPaths extracts API paths from .OwlBot.yaml deep-copy-regex
// source patterns by finding the base path and then discovering version
// directories in googleapis that contain a nodejs_gapic_library rule matching
// the provided npm package name.
func parseOwlBotAPIPaths(owlBot *owlBotYAML, googleapisDir, pkgName string) ([]*config.API, error) {
	if len(owlBot.DeepCopyRegex) == 0 {
		return nil, nil
	}
	// Use the first copy rule to find the base API path.
	source := owlBot.DeepCopyRegex[0].Source
	matches := owlBotSourceRegex.FindStringSubmatch(source)
	if len(matches) < 2 {
		return nil, fmt.Errorf("cannot parse API path from .OwlBot.yaml source: %q", source)
	}
	basePath := matches[1]
	if basePath == "" {
		basePath = matches[2]
	}

	// Find version directories in googleapis by walking the base path.
	dir := filepath.Join(googleapisDir, basePath)
	var apis []*config.API
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil // ignore inaccessible directories
		}
		if d.IsDir() {
			return nil
		}
		if d.Name() != "BUILD.bazel" {
			return nil
		}
		apiDir := filepath.Dir(path)
		apiPath, err := filepath.Rel(googleapisDir, apiDir)
		if err != nil {
			return fmt.Errorf("getting relative path for %s: %w", apiDir, err)
		}
		info, err := parseBazelNodejsInfo(googleapisDir, apiPath)
		if err != nil {
			return fmt.Errorf("parsing bazel info for %s: %w", apiPath, err)
		}
		if info == nil {
			return nil
		}
		// Match the npm package name.
		if info.packageName == pkgName {
			apis = append(apis, &config.API{Path: apiPath})
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walking googleapis directory %s: %w", dir, err)
	}
	sort.Slice(apis, func(i, j int) bool {
		return apis[i].Path < apis[j].Path
	})
	return apis, nil
}

// parseBazelNodejsInfo reads a BUILD.bazel file from the specified API
// directory (relative to googleapisDir) and extracts information from the
// nodejs_gapic_library rule. Returns nil if no such rule exists.
func parseBazelNodejsInfo(googleapisDir, apiDir string) (*nodejsGapicInfo, error) {
	file, err := parseBazel(googleapisDir, apiDir)
	if err != nil {
		return nil, err
	}
	if file == nil {
		return nil, nil
	}
	rules := file.Rules("nodejs_gapic_library")
	if len(rules) == 0 {
		return nil, nil
	}
	if len(rules) > 1 {
		return nil, fmt.Errorf("file %s/BUILD.bazel contains multiple nodejs_gapic_library rules", apiDir)
	}
	rule := rules[0]
	info := &nodejsGapicInfo{
		packageName:           rule.AttrString("package_name"),
		bundleConfig:          rule.AttrString("bundle_config"),
		extraProtocParameters: rule.AttrStrings("extra_protoc_parameters"),
		mainService:           rule.AttrString("main_service"),
		mixins:                rule.AttrString("mixins"),
	}
	if rule.AttrLiteral("diregapic") == "True" {
		info.diregapic = true
	}
	if rule.AttrLiteral("handwritten_layer") == "True" {
		info.handwrittenLayer = true
	}
	return info, nil
}

// copyrightYearRegex matches "Copyright YYYY Google" in a file header.
var copyrightYearRegex = regexp.MustCompile(`Copyright (\d{4}) Google`)

// versionDirRegex matches versioned directory names like v1, v2, v1beta1.
var versionDirRegex = regexp.MustCompile(`^v\d[a-z0-9]*`)

// extractCopyrightYear reads the copyright year from a versioned subdirectory
// of src/ (e.g. src/v1/index.ts), falling back to src/index.ts if no versioned
// directory exists.
func extractCopyrightYear(pkgDir string) string {
	srcDir := filepath.Join(pkgDir, "src")
	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return ""
	}
	var versionDirs []string
	for _, e := range entries {
		if e.IsDir() && versionDirRegex.MatchString(e.Name()) {
			versionDirs = append(versionDirs, e.Name())
		}
	}
	if len(versionDirs) > 0 {
		sort.Strings(versionDirs)
		data, err := os.ReadFile(filepath.Join(srcDir, versionDirs[0], "index.ts"))
		if err == nil {
			if m := copyrightYearRegex.FindSubmatch(data); len(m) > 1 {
				return string(m[1])
			}
		}
	}
	data, err := os.ReadFile(filepath.Join(srcDir, "index.ts"))
	if err != nil {
		return ""
	}
	if m := copyrightYearRegex.FindSubmatch(data); len(m) > 1 {
		return string(m[1])
	}
	return ""
}

// nodejsSubdirKeep walks the named subdirectory under pkgDir and returns all
// file paths relative to pkgDir, excluding anything under a generated/
// subdirectory. Returns nil if the subdirectory does not exist.
func nodejsSubdirKeep(pkgDir, subdir string) ([]string, error) {
	dir := filepath.Join(pkgDir, subdir)
	if _, err := os.Stat(dir); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, err
	}
	var paths []string
	err := filepath.WalkDir(dir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if filepath.Base(path) == "generated" {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(pkgDir, path)
		if err != nil {
			return fmt.Errorf("getting relative path for %s: %w", path, err)
		}
		paths = append(paths, rel)
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)
	return paths, nil
}

// deriveNpmPackageName derives the expected npm package name from a library
// directory name. For example, "google-cloud-batch" becomes
// "@google-cloud/batch".
func deriveNpmPackageName(libraryName string) string {
	idx := strings.Index(libraryName, "-")
	if idx == -1 {
		return libraryName
	}
	idx2 := strings.Index(libraryName[idx+1:], "-")
	if idx2 == -1 {
		return libraryName
	}
	idx2 += idx + 1
	scope := libraryName[:idx2]
	name := libraryName[idx2+1:]
	return fmt.Sprintf("@%s/%s", scope, name)
}
