// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package surfer

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/googleapis/librarian/internal/sidekick/surfer/declarative"
	"github.com/googleapis/librarian/internal/yaml"
	"github.com/iancoleman/strcase"
)

// partialsHeader is the directive that tells gcloud to look in the `_partials` directory
// for command definitions. This allows for sharing definitions across release tracks.
const partialsHeader = "_PARTIALS_: true\n"

const licenseTemplate = `# -*- coding: utf-8 -*- #
# Copyright {{.Year}} Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
`

const autogenTemplate = licenseTemplate + `#
# NOTE: This file is autogenerated and should not be edited by hand.
`

func header() string {
	var buf bytes.Buffer
	t := template.Must(template.New("header").Parse(autogenTemplate))
	t.Execute(&buf, map[string]interface{}{"Year": time.Now().Year()})
	return buf.String()
}

func writeCommandFiles(resourceDir string, verb string, cmd *Command, tracks []ReleaseTrack) error {
	if cmd == nil || len(tracks) == 0 {
		return nil
	}

	partialsDir := filepath.Join(resourceDir, "_partials")
	if err := os.MkdirAll(partialsDir, 0755); err != nil {
		return fmt.Errorf("failed to create partials directory: %w", err)
	}

	mainCmdPath := filepath.Join(resourceDir, fmt.Sprintf("%s.yaml", verb))
	if err := os.WriteFile(mainCmdPath, []byte(header()+partialsHeader), 0644); err != nil {
		return fmt.Errorf("failed to write main command file for %q: %w", verb, err)
	}

	for _, track := range tracks {
		if err := writePartialFile(partialsDir, verb, track, cmd); err != nil {
			return err
		}
	}

	return nil
}

func writePartialFile(partialsDir string, verb string, track ReleaseTrack, cmd *Command) error {
	if cmd == nil {
		return nil
	}

	b, err := marshalCommand(cmd, track)
	if err != nil {
		return fmt.Errorf("failed to marshal partial command for %q in %s track: %w", verb, track, err)
	}

	trackName := strings.ToLower(string(track))
	partialFileName := fmt.Sprintf("_%s_%s.yaml", verb, trackName)
	partialCmdPath := filepath.Join(partialsDir, partialFileName)

	fullContent := append([]byte(header()), b...)
	if err := os.WriteFile(partialCmdPath, fullContent, 0644); err != nil {
		return fmt.Errorf("failed to write partial command file for %q: %w", verb, err)
	}
	return nil
}

// marshalCommand converts a Command into a YAML byte payload matching the schema.
func marshalCommand(cmd *Command, track ReleaseTrack) ([]byte, error) {
	yamlCmd := mapCommandToYAML(cmd, track)
	cmdList := []*declarative.Command{yamlCmd}
	return yaml.Marshal(cmdList)
}

func mapCommandToYAML(c *Command, track ReleaseTrack) *declarative.Command {
	y := &declarative.Command{
		ReleaseTracks: []string{string(track)},
		AutoGenerated: true,
		Hidden:        c.Hidden,
		HelpText: declarative.HelpText{
			Brief:       c.HelpText.Brief,
			Description: c.HelpText.Description,
			Examples:    c.HelpText.Examples,
		},
		Arguments: declarative.Arguments{
			Params: mapArgumentsToYAML(c.Arguments),
		},
	}
	if c.APIVersion != "" || len(c.Collection) > 0 || c.Method != "" || c.StarUpdateMask {
		var staticFields map[string]string
		if c.StarUpdateMask {
			staticFields = map[string]string{"updateMask": "*"}
		}
		y.Request = &declarative.Request{
			APIVersion:   c.APIVersion,
			Collection:   c.Collection,
			Method:       c.Method,
			StaticFields: staticFields,
		}
	}
	if c.Async != nil {
		y.Async = &declarative.Async{
			Collection:            c.Async.Collection,
			ExtractResourceResult: c.Async.ExtractResourceResult,
		}
	}
	if c.ResponseIDField != "" {
		y.Response = &declarative.Response{
			IDField: c.ResponseIDField,
		}
	}
	if c.ReadModifyUpdate || c.DisableAutoFieldMask {
		y.Update = &declarative.Update{
			ReadModifyUpdate:     c.ReadModifyUpdate,
			DisableAutoFieldMask: c.DisableAutoFieldMask,
		}
	}
	if c.OutputFormat != "" {
		y.Output = &declarative.Output{
			Format: c.OutputFormat,
		}
	}
	return y
}

func mapArgumentsToYAML(args []Argument) []declarative.Argument {
	var ya []declarative.Argument
	for _, a := range args {
		t := a.Type
		if t == "str" {
			t = ""
		}
		var def declarative.Default
		if a.Action == "store_true" {
			var nilVal any = nil
			def.Value = &nilVal
		}
		var apiField string
		var rmp map[string]string

		if len(a.APIField) > 0 {
			parts := make([]string, len(a.APIField))
			for i, p := range a.APIField {
				parts[i] = strcase.ToLowerCamel(p)
			}
			joinedPath := strings.Join(parts, ".")

			if a.ResourceSpec != nil {
				rmp = map[string]string{
					joinedPath: "{__relative_name__}",
				}
			} else {
				apiField = joinedPath
			}
		}

		ya = append(ya, declarative.Argument{
			ArgName:              strcase.ToKebab(a.ArgName),
			APIField:             apiField,
			HelpText:             a.HelpText,
			Action:               a.Action,
			Default:              def,
			IsPositional:         a.IsPositional,
			IsPrimaryResource:    a.IsPrimaryResource,
			RequestIDField:       a.RequestIDField,
			ResourceSpec:         mapResourceSpecToYAML(a.ResourceSpec),
			Required:             a.Required,
			Repeated:             a.Repeated,
			Clearable:            a.Clearable,
			Type:                 t,
			Choices:              mapChoicesToYAML(a.Choices),
			Spec:                 mapArgSpecsToYAML(a.Spec),
			ResourceMethodParams: rmp,
		})
	}
	return ya
}

func mapResourceSpecToYAML(spec *ResourceSpec) *declarative.ResourceSpec {
	if spec == nil {
		return nil
	}
	var attrs []declarative.Attribute
	for _, a := range spec.Attributes {
		attrs = append(attrs, declarative.Attribute{
			AttributeName: strcase.ToSnake(a.AttributeName),
			ParameterName: a.ParameterName,
			Help:          a.Help,
			Property:      a.Property,
		})
	}
	return &declarative.ResourceSpec{
		Name:                  spec.Name,
		PluralName:            spec.PluralName,
		Collection:            spec.Collection,
		Attributes:            attrs,
		DisableAutoCompleters: spec.DisableAutoCompleters,
	}
}

func mapArgSpecsToYAML(specs []ArgSpec) []declarative.ArgSpec {
	var yamlSpecs []declarative.ArgSpec
	for _, s := range specs {
		yamlSpecs = append(yamlSpecs, declarative.ArgSpec(s))
	}
	return yamlSpecs
}

func mapChoicesToYAML(choices []Choice) []declarative.Choice {
	var yamlChoices []declarative.Choice
	for _, c := range choices {
		yamlChoices = append(yamlChoices, declarative.Choice(c))
	}
	return yamlChoices
}
