// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package surfer

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/sidekick/surfer/declarative"
)

func TestWritePartialFile_Output(t *testing.T) {
	tmpDir := t.TempDir()
	cmd := &Command{
		HelpText: HelpText{
			Brief: "Test command",
		},
	}

	err := writePartialFile(tmpDir, "test", GA, cmd)
	if err != nil {
		t.Fatalf("writePartialFile unexpected error: %v", err)
	}

	partialPath := filepath.Join(tmpDir, "_test_ga.yaml")
	data, err := os.ReadFile(partialPath)
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	got := string(data)
	year := time.Now().Year()

	want := fmt.Sprintf(`# -*- coding: utf-8 -*- #
# Copyright %d Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This file is autogenerated and should not be edited by hand.
- release_tracks:
    - GA
  auto_generated: true
  help_text:
    brief: Test command
    description: ""
  arguments: {}
`, year)

	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("writePartialFile output mismatch (-want +got):\n%s", diff)
	}
}

func TestMarshalCommand(t *testing.T) {
	cmd := &Command{
		Arguments: []Argument{
			{
				ArgName: "test-arg",
				Type:    "string",
			},
		},
	}

	b, err := marshalCommand(cmd, GA)
	if err != nil {
		t.Fatalf("marshalCommand() unexpected error: %v", err)
	}

	got := string(b)
	want := `- release_tracks:
    - GA
  auto_generated: true
  help_text:
    brief: ""
    description: ""
  arguments:
    params:
      - arg_name: test-arg
        help_text: ""
        is_positional: false
        required: false
        type: string
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Logf("Got:\n%s", got)
		t.Errorf("marshalCommand() mismatch (-want +got):\n%s", diff)
	}
}

func TestWriteCommandFiles(t *testing.T) {
	tmpDir := t.TempDir()
	verb := "create"

	if err := writeCommandFiles(tmpDir, verb, &Command{}, []ReleaseTrack{GA, Beta}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(tmpDir, "create.yaml"),
		filepath.Join(tmpDir, "_partials", "_create_beta.yaml"),
		filepath.Join(tmpDir, "_partials", "_create_ga.yaml"),
	}

	for _, f := range expectedFiles {
		if _, err := os.Stat(f); errors.Is(err, fs.ErrNotExist) {
			t.Errorf("expected file %q to be generated", f)
		}
	}
}

func TestWriteCommandFiles_Error(t *testing.T) {
	err := writeCommandFiles("/dev/null/invalid/path", "create", &Command{}, []ReleaseTrack{GA})
	if err == nil {
		t.Error("expected error writing to invalid path, got nil")
	}
}

func TestMapCommandToYAML(t *testing.T) {
	var nilVal any = nil
	cmd := &Command{
		Hidden: true,
		HelpText: HelpText{
			Brief:       "brief",
			Description: "desc",
			Examples:    "ex",
		},
		Collection: []string{"c"},
		APIVersion: "v1",
		Method:     "m",
		Async: &Async{
			Collection:            []string{"ac"},
			ExtractResourceResult: true,
		},
		ReadModifyUpdate:     true,
		DisableAutoFieldMask: true,
		StarUpdateMask:       true,
		ResponseIDField:      "id",
		OutputFormat:         "table",
		Arguments: []Argument{
			{
				ArgName: "arg",
				Type:    "str",
				Spec: []ArgSpec{
					{APIField: "s"},
				},
				Choices: []Choice{
					{ArgValue: "av", EnumValue: "ev", HelpText: "ch"},
				},
				ResourceSpec: &ResourceSpec{
					Name:       "resource_name",
					PluralName: "resource_plural",
					Collection: "c",
					Attributes: []Attribute{
						{AttributeName: "attributeName"},
					},
					DisableAutoCompleters: true,
				},
			},
			{
				ArgName: "bool-arg",
				Type:    "bool",
				Action:  "store_true",
			},
			{
				ArgName:  "arg-with-apifield",
				Type:     "str",
				APIField: []string{"Part1", "Part2"},
			},
			{
				ArgName:  "arg-with-apifield-and-resource",
				Type:     "str",
				APIField: []string{"Part1", "Part2"},
				ResourceSpec: &ResourceSpec{
					Name: "nested_resource",
				},
			},
		},
	}

	yCmd := mapCommandToYAML(cmd, GA)
	if yCmd.AutoGenerated != true {
		t.Errorf("AutoGenerated = false, want true")
	}

	want := &declarative.Command{
		ReleaseTracks: []string{"GA"},
		AutoGenerated: true,
		Hidden:        true,
		HelpText: declarative.HelpText{
			Brief:       "brief",
			Description: "desc",
			Examples:    "ex",
		},
		Request: &declarative.Request{
			Collection:   []string{"c"},
			APIVersion:   "v1",
			Method:       "m",
			StaticFields: map[string]string{"updateMask": "*"},
		},
		Async: &declarative.Async{
			Collection:            []string{"ac"},
			ExtractResourceResult: true,
		},
		Update: &declarative.Update{
			ReadModifyUpdate:     true,
			DisableAutoFieldMask: true,
		},
		Response: &declarative.Response{
			IDField: "id",
		},
		Output: &declarative.Output{
			Format: "table",
		},
		Arguments: declarative.Arguments{
			Params: []declarative.Argument{
				{
					ArgName: "arg",
					Spec: []declarative.ArgSpec{
						{APIField: "s"},
					},
					Choices: []declarative.Choice{
						{ArgValue: "av", EnumValue: "ev", HelpText: "ch"},
					},
					ResourceSpec: &declarative.ResourceSpec{
						Name:       "resourceName",
						PluralName: "resourcePlural",
						Collection: "c",
						Attributes: []declarative.Attribute{
							{AttributeName: "attribute_name"},
						},
						DisableAutoCompleters: true,
					},
				},
				{
					ArgName: "bool-arg",
					Type:    "bool",
					Action:  "store_true",
					Default: declarative.Default{Value: &nilVal},
				},
				{
					ArgName:  "arg-with-apifield",
					APIField: "part1.part2",
				},
				{
					ArgName: "arg-with-apifield-and-resource",
					ResourceSpec: &declarative.ResourceSpec{
						Name: "nestedResource",
					},
					ResourceMethodParams: map[string]string{
						"part1.part2": "{__relative_name__}",
					},
				},
			},
		},
	}
	if diff := cmp.Diff(want, yCmd); diff != "" {
		t.Errorf("mismatch (-want +got):\n%s", diff)
	}
}
