// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package surfer

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestRenderCommandGroup(t *testing.T) {
	data := commandGroupView{
		ClassName:  "instances",
		ModulePath: "googlecloudsdk.surface.instances",
		HelpText:   "Manage Compute Engine Instance resources.",
		Year:       2025,
		Tracks: []trackView{
			{Name: "GA", Suffix: "Ga"},
			{Name: "BETA", Suffix: "Beta"},
		},
	}

	var buf bytes.Buffer
	err := commandGroupTemplate.Execute(&buf, data)
	if err != nil {
		t.Fatalf("commandGroupTemplate.Execute() unexpected error: %v", err)
	}
	got := strings.TrimSpace(buf.String()) + "\n"

	want := `# -*- coding: utf-8 -*- #
# Copyright 2025 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Compute Engine Instance resources."""

from googlecloudsdk.calliope import base
from googlecloudsdk.surface.instances import _init_extensions as extensions


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
class InstancesGa(extensions.InstancesGa):
  """Manage Compute Engine Instance resources."""


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
class InstancesBeta(extensions.InstancesBeta):
  """Manage Compute Engine Instance resources."""
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Logf("Got:\n%s", got)
		t.Errorf("renderCommandGroup() mismatch (-want +got):\n%s", diff)
	}
}

func TestRenderInitExtensions(t *testing.T) {
	data := commandGroupView{
		ClassName:  "instances",
		ModulePath: "googlecloudsdk.surface.instances",
		HelpText:   "Manage Compute Engine Instance resources.",
		Year:       2025,
		IsRoot:     false,
	}

	var buf bytes.Buffer
	err := initExtensionsTemplate.Execute(&buf, data)
	if err != nil {
		t.Fatalf("initExtensionsTemplate.Execute() unexpected error: %v", err)
	}
	got := buf.String()

	want := `# -*- coding: utf-8 -*- #
# Copyright 2025 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""File to add optional custom code to extend __init__.py."""
from googlecloudsdk.calliope import base


class InstancesAlpha(base.Group):
  """Optional no-auto-generated code for ALPHA."""


class InstancesBeta(base.Group):
  """Optional no-auto-generated code for BETA."""


class InstancesGa(base.Group):
  """Optional no-auto-generated code for GA."""
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Logf("Got:\n%s", got)
		t.Errorf("initExtensionsTemplate.Execute() mismatch (-want +got):\n%s", diff)
	}
}

func TestWriteCommandGroupFile(t *testing.T) {
	tmpDir := t.TempDir()
	ga := &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "Manage instances"}
	cfg := &SurfaceWriterConfig{OutputDir: tmpDir, BaseModule: "googlecloudsdk.instances", Tracks: []ReleaseTrack{GA}}
	if err := writeCommandGroupFile(cfg, ga, []string{"instances"}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedPath := filepath.Join(tmpDir, "instances", "__init__.py")
	if _, err := os.Stat(expectedPath); errors.Is(err, fs.ErrNotExist) {
		t.Errorf("expected file %q to be generated", expectedPath)
	}
}

func TestWriteCommandGroupFile_Error(t *testing.T) {
	ga := &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "Manage instances"}
	cfg := &SurfaceWriterConfig{OutputDir: "/dev/null/invalid/path", BaseModule: "googlecloudsdk.instances", Tracks: []ReleaseTrack{GA}}
	err := writeCommandGroupFile(cfg, ga, []string{"instances"})
	if err == nil {
		t.Error("expected error writing to invalid path, got nil")
	}
}

func TestWriteSurface(t *testing.T) {
	tmpDir := t.TempDir()

	surface := &Surface{
		Root: &CommandGroup{
			ClassName: "users",
			FileName:  "users",
			HelpText:  "Manage users.",
			Commands: map[string]*Command{
				"create": {},
			},
			Groups: map[string]*CommandGroup{
				"billing": {
					ClassName: "billing",
					FileName:  "billing",
					HelpText:  "Manage user billing.",
					Commands: map[string]*Command{
						"cancel": {},
					},
				},
			},
		},
		Tracks: []ReleaseTrack{GA},
	}

	if err := writeSurface(tmpDir, "googlecloudsdk", surface); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(tmpDir, "users", "__init__.py"),
		filepath.Join(tmpDir, "users", "billing", "__init__.py"),
		filepath.Join(tmpDir, "users", "billing", "cancel.yaml"),
		filepath.Join(tmpDir, "users", "billing", "_partials", "_cancel_ga.yaml"),
	}

	for _, f := range expectedFiles {
		if _, err := os.Stat(f); errors.Is(err, fs.ErrNotExist) {
			t.Errorf("expected file %q to be generated", f)
		}
	}
}

func TestWriteCommandGroupFile_TrackCombinations(t *testing.T) {
	tmpDir := t.TempDir()

	tests := []struct {
		name           string
		ga             *CommandGroup
		beta           *CommandGroup
		alpha          *CommandGroup
		containsTracks []string
		omitsTracks    []string
	}{
		{
			name:           "GA and Beta",
			ga:             &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "G"},
			beta:           &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "B"},
			containsTracks: []string{"ReleaseTrack.GA", "ReleaseTrack.BETA"},
			omitsTracks:    []string{"ReleaseTrack.ALPHA"},
		},
		{
			name:           "Beta and Alpha",
			beta:           &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "B"},
			alpha:          &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "A"},
			containsTracks: []string{"ReleaseTrack.BETA", "ReleaseTrack.ALPHA"},
			omitsTracks:    []string{"ReleaseTrack.GA"},
		},
		{
			name:           "Only Alpha",
			alpha:          &CommandGroup{ClassName: "instances", FileName: "instances", HelpText: "A"},
			containsTracks: []string{"ReleaseTrack.ALPHA"},
			omitsTracks:    []string{"ReleaseTrack.GA", "ReleaseTrack.BETA"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var g *CommandGroup
			var tracks []ReleaseTrack
			if tt.ga != nil {
				g = tt.ga
				tracks = append(tracks, GA)
			}
			if tt.beta != nil {
				g = tt.beta
				tracks = append(tracks, Beta)
			}
			if tt.alpha != nil {
				g = tt.alpha
				tracks = append(tracks, Alpha)
			}

			cfg := &SurfaceWriterConfig{OutputDir: tmpDir, BaseModule: "googlecloudsdk.instances", Tracks: tracks}
			if err := writeCommandGroupFile(cfg, g, []string{"instances"}); err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			path := filepath.Join(tmpDir, "instances", "__init__.py")
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("failed to read generated file: %v", err)
			}

			content := string(data)
			for _, track := range tt.containsTracks {
				if !strings.Contains(content, track) {
					t.Errorf("expected content to contain %q", track)
				}
			}
			for _, track := range tt.omitsTracks {
				if strings.Contains(content, track) {
					t.Errorf("expected content to NOT contain %q", track)
				}
			}
		})
	}
}

func TestWriteGroup_DirError(t *testing.T) {
	// Trying to create a directory where a file already exists should fail
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "instances")
	if err := os.WriteFile(filePath, []byte("test"), 0644); err != nil {
		t.Fatalf("failed to create test file: %v", err)
	}

	ga := &CommandGroup{ClassName: "instances", FileName: "instances"}
	cfg := &SurfaceWriterConfig{OutputDir: tmpDir, BaseModule: "googlecloudsdk", Tracks: []ReleaseTrack{GA}}
	err := writeGroup(cfg, ga, nil)
	if err == nil {
		t.Error("expected error when creating directory over an existing file, got nil")
	}
}

func TestWriteGroup_NoName(t *testing.T) {
	tmpDir := t.TempDir()
	cfg := &SurfaceWriterConfig{OutputDir: tmpDir, BaseModule: "googlecloudsdk", Tracks: []ReleaseTrack{}}
	err := writeGroup(cfg, nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should not generate any files or directories
	entries, err := os.ReadDir(tmpDir)
	if err != nil {
		t.Fatalf("failed to read dir: %v", err)
	}
	if len(entries) != 0 {
		t.Errorf("expected empty directory, got %d entries", len(entries))
	}
}
