# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Linter
on: [push, pull_request, merge_group]
permissions:
  contents: read
jobs:
  addlicense:
    runs-on: ubuntu-24.04
    # Presubmit jobs must complete within 5 minutes. See CONTRIBUTING.md.
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Run TestAddLicense
        run: go test -run TestAddLicense -count=1 .
  typos:
    runs-on: ubuntu-24.04
    # Presubmit jobs must complete within 5 minutes. See CONTRIBUTING.md.
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@v1.45.0
  yamlfmt:
    runs-on: ubuntu-24.04
    # Presubmit jobs must complete within 5 minutes. See CONTRIBUTING.md.
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Run TestYAMLFormat
        run: go test -run TestYAMLFormat -count=1 .
